---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aliaflex/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp envia.php $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
